---
title: "minefield generator"
author: "Bram van Smoorenburg"
date: "27 November 2018"
output: html_document
---

```{r}
height=16
width=50
minesfrac=0.5
savefields=TRUE
allowerrors=TRUE
mintiles=10 #minimum number of cleared tiles until the algorithm saves the field
set.seed(20181205)
```

```{r}
edgewidth=5
squarewidth=20
```

```{r}
library(png)
library(xlsx)
if (savefields) {
  dir.create("./Minesweeper Loops Output")
}
```

#functions
index matrix
```{r}
mx.ind <- function (mx) {
  cbind(        # create a 2 wide matrix of all possible indices in input
    rep(seq.int(nrow(mx)), ncol(mx)), 
    rep(seq.int(ncol(mx)), each=nrow(mx))
  )}
```

compute neighbors
```{r}
compute_neighb_sum <- function(mx) {
  mx.ind <- cbind(        # create a 2 wide matrix of all possible indices in input
    rep(seq.int(nrow(mx)), ncol(mx)), 
    rep(seq.int(ncol(mx)), each=nrow(mx))
  )
  sum_neighb_each <- function(x) {
    near.ind <- cbind(         # for each x, y coord, create an index of all surrounding values
      rep(x[[1]] + -1:1, 3),
      rep(x[[2]] + -1:1, each=3)
    )
    near.ind.val <- near.ind[  # eliminate out of bound values, or the actual x,y coord itself
      !(
        near.ind[, 1] < 1 | near.ind[, 1] > nrow(mx)  |
        near.ind[, 2] < 1 | near.ind[, 2] > ncol(mx)  |
        (near.ind[, 1] == x[[1]] & near.ind[, 2] == x[[2]])
      ),
     ]
    sum(mx[near.ind.val])      # Now sum the surrounding cell values
  }
  `dim<-`(                     # this is just to return in same matrix format as input
    sapply(
      split(mx.ind, row(mx.ind)),   # For each x, y coordinate in input mx
      sum_neighb_each               # compute the neighbor sum
    ),
    c(nrow(mx), ncol(mx))      # dimensions of input
  )  
}
compute_neighb_prod <- function(mx) {
  mx.ind <- cbind(        # create a 2 wide matrix of all possible indices in input
    rep(seq.int(nrow(mx)), ncol(mx)), 
    rep(seq.int(ncol(mx)), each=nrow(mx))
  )
  sum_neighb_each <- function(x) {
    near.ind <- cbind(         # for each x, y coord, create an index of all surrounding values
      rep(x[[1]] + -1:1, 3),
      rep(x[[2]] + -1:1, each=3)
    )
    near.ind.val <- near.ind[  # eliminate out of bound values, or the actual x,y coord itself
      !(
        near.ind[, 1] < 1 | near.ind[, 1] > nrow(mx)  |
        near.ind[, 2] < 1 | near.ind[, 2] > ncol(mx)  |
        (near.ind[, 1] == x[[1]] & near.ind[, 2] == x[[2]])
      ),
     ]
    prod(mx[near.ind.val])      # Now sum the surrounding cell values
  }
  `dim<-`(                     # this is just to return in same matrix format as input
    sapply(
      split(mx.ind, row(mx.ind)),   # For each x, y coordinate in input mx
      sum_neighb_each               # compute the neighbor sum
    ),
    c(nrow(mx), ncol(mx))      # dimensions of input
  )  
}
compute_neighb_max <- function(mx) {
  mx.ind <- cbind(        # create a 2 wide matrix of all possible indices in input
    rep(seq.int(nrow(mx)), ncol(mx)), 
    rep(seq.int(ncol(mx)), each=nrow(mx))
  )
  sum_neighb_each <- function(x) {
    near.ind <- cbind(         # for each x, y coord, create an index of all surrounding values
      rep(x[[1]] + -1:1, 3),
      rep(x[[2]] + -1:1, each=3)
    )
    near.ind.val <- near.ind[  # eliminate out of bound values, or the actual x,y coord itself
      !(
        near.ind[, 1] < 1 | near.ind[, 1] > nrow(mx)  |
        near.ind[, 2] < 1 | near.ind[, 2] > ncol(mx)  |
        (near.ind[, 1] == x[[1]] & near.ind[, 2] == x[[2]])
      ),
     ]
    max(mx[near.ind.val])      # Now max the surrounding cell values
  }
  `dim<-`(                     # this is just to return in same matrix format as input
    sapply(
      split(mx.ind, row(mx.ind)),   # For each x, y coordinate in input mx
      sum_neighb_each               # compute the neighbor sum
    ),
    c(nrow(mx), ncol(mx))      # dimensions of input
  )  
}
```

generating primes
```{r}
getprimes=function(n) {
  out=c(2,3)
  i=3
  while (length(out)<n) {
    i=i+2
    if (all(i%%(2:sqrt(i))!=0)) {
      out[length(out)+1]=i
    }
  }
  return(out)
}
```

color scheme:
0:  255 255 255 (0 tile)
pi: 192 192 192 (unopened tile)
10: 128   0 255 (mine)
e: 255 255   0 (flag)
1:    0   0 255
2:    0 128   0
3:  255   0   0
4:    0   0 128
5:  128   0   0
6:    0 128 128
7:    0   0   0
8:  128 128 128

```{r}
coloring=function(x,mat=field,ed=edgewidth,sq=squarewidth) {
  rowx=x[1]
  colx=x[2]
  rowloc=(rowx-1)*sq+(rowx-1)*ed+1
  colloc=(colx-1)*sq+(colx-1)*ed+1
  
  if (mat[rowx,colx]==pi) {
    fieldimg[rowloc:(rowloc+sq-1),colloc:(colloc+sq-1),]<<-192
  } else if (mat[rowx,colx]==0) {
    fieldimg[rowloc:(rowloc+sq-1),colloc:(colloc+sq-1),]<<-255
  } else if (mat[rowx,colx]==exp(1)) {
    fieldimg[rowloc:(rowloc+sq-1),colloc:(colloc+sq-1),]<<-c(rep(255,sq^2),rep(255,sq^2),rep(0,sq^2))
  } else if (mat[rowx,colx]==1) {
    fieldimg[rowloc:(rowloc+sq-1),colloc:(colloc+sq-1),]<<-c(rep(0,sq^2),rep(0,sq^2),rep(255,sq^2))
  } else if (mat[rowx,colx]==2) {
    fieldimg[rowloc:(rowloc+sq-1),colloc:(colloc+sq-1),]<<-c(rep(0,sq^2),rep(128,sq^2),rep(0,sq^2))
  } else if (mat[rowx,colx]==3) {
    fieldimg[rowloc:(rowloc+sq-1),colloc:(colloc+sq-1),]<<-c(rep(255,sq^2),rep(0,sq^2),rep(0,sq^2))
  } else if (mat[rowx,colx]==10) {
    fieldimg[rowloc:(rowloc+sq-1),colloc:(colloc+sq-1),]<<-c(rep(128,sq^2),rep(0,sq^2),rep(255,sq^2))
  } else if (mat[rowx,colx]==4) {
    fieldimg[rowloc:(rowloc+sq-1),colloc:(colloc+sq-1),]<<-c(rep(0,sq^2),rep(0,sq^2),rep(128,sq^2))
  } else if (mat[rowx,colx]==5) {
    fieldimg[rowloc:(rowloc+sq-1),colloc:(colloc+sq-1),]<<-c(rep(128,sq^2),rep(0,sq^2),rep(0,sq^2))
  } else if (mat[rowx,colx]==6) {
    fieldimg[rowloc:(rowloc+sq-1),colloc:(colloc+sq-1),]<<-c(rep(0,sq^2),rep(128,sq^2),rep(128,sq^2))
  } else if (mat[rowx,colx]==8) {
    fieldimg[rowloc:(rowloc+sq-1),colloc:(colloc+sq-1),]<<-128
  }
}
```

#looping
```{r}
if (savefields) {
  setwd("./Minesweeper Loops Output")
}
totmines=ceiling(minesfrac*height*width)
fielddims=c(height*squarewidth+(height-1)*edgewidth,width*squarewidth+(width-1)*edgewidth,3)
flags=numeric(0)
clearedtiles=numeric(0)
errors=numeric(0)
it=0
repeat {
  it=it+1
  fieldrand=matrix(runif(prod(height,width)),ncol = width)
fieldrand[1,width]=fieldrand[2,width]=1
fieldmines=fieldrand-fieldrand
fieldmines[rank(fieldrand,ties.method = "random")<=totmines]=1
fieldsolved=compute_neighb_sum(fieldmines)
fieldsolved[fieldmines==1]=10
field=fieldsolved-fieldsolved+pi
field[1,width]=fieldsolved[1,width]
field[2,width]=fieldsolved[2,width]
fieldprod=compute_neighb_prod(field)
fieldtiles=compute_neighb_sum(field==pi)
fieldflags=compute_neighb_sum(field==exp(1)|field==10)
fieldhist=field

repeat {
  repeat {
  fieldhist2=field
  if (any(fieldprod==0)) { #sweep all tiles surrounded by 0
  fieldhist3=field
  repeat {
    field[fieldprod==0]=fieldsolved[fieldprod==0]
    fieldprod=compute_neighb_prod(field)
    if (all(fieldhist3==field)) {
      fieldtiles=compute_neighb_sum(field==pi)
      fieldflags=compute_neighb_sum(field==exp(1)|field==10)
      break
    }
    fieldhist3=field
  }
  }
  
  if (any(field>0&fieldtiles>0&fieldtiles==field-fieldflags)) { #add flags to tiles
  fieldhist3=field
  repeat {
    field[compute_neighb_sum(fieldtiles==field-fieldflags)>0&field==pi]=exp(1)
    fieldtiles=compute_neighb_sum(field==pi)
    fieldflags=compute_neighb_sum(field==exp(1)|field==10)
    if (all(fieldhist3==field)) {
      fieldprod=compute_neighb_prod(field)
      break
    }
    fieldhist3=field
  }
}
  
  if (any(field!=0&field-fieldflags==0&fieldtiles>0)) { #sweep tiles with tiles equal to mines minus flags
      fieldhist3=field
      repeat {
        field[compute_neighb_sum(field!=0&field-fieldflags==0&fieldtiles>0)&field==pi]=fieldsolved[compute_neighb_sum(field!=0&field-fieldflags==0&fieldtiles>0)&field==pi]
        fieldtiles=compute_neighb_sum(field==pi)
        fieldflags=compute_neighb_sum(field==exp(1)|field==10)
        if (all(fieldhist3==field)) {
          fieldprod=compute_neighb_prod(field)
          break
        }
        fieldhist3=field
      }
    }

  if (all(fieldhist2==field)) {
    fieldsum=compute_neighb_sum(field)
    fieldnums=field==trunc(field)&fieldtiles>0&field!=10
    fieldmoves=(compute_neighb_sum(fieldnums)*(field==pi))>0
    break
  }
  fieldhist2=field
  }
  
  if (sum(field==pi)>0&sum(field==pi)+sum(field==10|field==exp(1))==totmines) { #if all remaining unopened tiles are guaranteed to contain mines, flag them all
    field[field==pi]=exp(1)
    fieldprod=compute_neighb_prod(field)
    fieldtiles=compute_neighb_sum(field==pi)
    fieldflags=compute_neighb_sum(field==exp(1)|field==10)
  }
  
  if (sum(field==pi)>0&sum(fieldnums)>0) { #sweeping tiles of numbers that are nested in other numbers
  primeset=sample(getprimes(sum(fieldmoves)))
  primefield=field-field+1
  primefield[fieldmoves]=primeset
  primefield2=compute_neighb_prod(primefield)*fieldnums
  if (any(primefield2>1e14)) {
    for (n in 1:1e3) {
      if (any(primefield2>1e14)) {
        primefield=field-field+1
      primefield[fieldmoves]=sample(primeset)
      primefield2=compute_neighb_prod(primefield)*fieldnums
      } else {
        break
      }
    }
    if (any(primefield2>1e14)) {
      primefield2[primefield2>1e14]=0
    }
  }
  primenums=sort(unique(as.vector(primefield2)))[-1]
  primebingo=numeric(0)
  if (length(primenums)>1) {
    for (i in 2:length(primenums)) {
    if (any(primenums[i]%%primenums[1:(i-1)]==0)) {
      primebingo[length(primebingo)+1]=primenums[i]
    }
  }
  }
  
  if (length(primebingo)>0) {
    for (i in primebingo) {
      fieldbingo=which(primefield2==i)[1]
      fieldbingo2=which(i%%primefield2==0&primefield2!=i)[1]
      if (field[fieldbingo2]-fieldflags[fieldbingo2]==field[fieldbingo]-fieldflags[fieldbingo]&fieldtiles[fieldbingo]>fieldtiles[fieldbingo2]) {
        field[field==pi&compute_neighb_sum(primefield2==primefield2[fieldbingo])&!compute_neighb_sum(primefield2==primefield2[fieldbingo2])]=fieldsolved[field==pi&compute_neighb_sum(primefield2==primefield2[fieldbingo])&!compute_neighb_sum(primefield2==primefield2[fieldbingo2])]
      } else if (field[fieldbingo2]-fieldflags[fieldbingo2]==field[fieldbingo]-fieldflags[fieldbingo]&fieldtiles[fieldbingo]<fieldtiles[fieldbingo2]) {
        field[field==pi&compute_neighb_sum(primefield2==primefield2[fieldbingo2])&!compute_neighb_sum(primefield2==primefield2[fieldbingo])]=fieldsolved[field==pi&compute_neighb_sum(primefield2==primefield2[fieldbingo2])&!compute_neighb_sum(primefield2==primefield2[fieldbingo])]
      } else if (fieldtiles[fieldbingo]==fieldtiles[fieldbingo2]+field[fieldbingo]-fieldflags[fieldbingo]-(field[fieldbingo2]-fieldflags[fieldbingo2])) {
        field[field==pi&compute_neighb_sum(primefield2==primefield2[fieldbingo])&!compute_neighb_sum(primefield2==primefield2[fieldbingo2])]=exp(1)
      } else if (fieldtiles[fieldbingo2]==fieldtiles[fieldbingo]+field[fieldbingo2]-fieldflags[fieldbingo2]-(field[fieldbingo]-fieldflags[fieldbingo])) {
        field[field==pi&compute_neighb_sum(primefield2==primefield2[fieldbingo2])&!compute_neighb_sum(primefield2==primefield2[fieldbingo])]=exp(1)
      }
    }
    fieldprod=compute_neighb_prod(field)
    fieldtiles=compute_neighb_sum(field==pi)
    fieldflags=compute_neighb_sum(field==exp(1)|field==10)
  }
  }
  
  fieldnums=field==trunc(field)&fieldtiles>0&field!=10
  if (all(fieldhist==field)&allowerrors&sum(field==pi)>0) { #randomly sweep tiles with lowest probability of containing a mine, if errors are allowed
    if (sum(fieldnums)>0) {
      fieldsum=compute_neighb_sum(field)
    fieldmoves=(compute_neighb_sum(fieldnums)*(field==pi))>0
    minesprob=compute_neighb_max(fieldnums*(field-fieldflags)/fieldtiles)*fieldmoves
    minesprob[is.nan(minesprob)]=1
    minesprob[minesprob==0]=1
    minprob=which.min(minesprob)
    } else {
      minprob=compute_neighb_sum(field==exp(1)|field==10)*(field==pi)
      if (any(minprob!=0&minprob!=8)) {
        minprob[minprob==8]=0
      }
      minprob=which.max(minprob)
    }
    field[minprob]=fieldsolved[minprob]
    fieldprod=compute_neighb_prod(field)
    fieldtiles=compute_neighb_sum(field==pi)
    fieldflags=compute_neighb_sum(field==exp(1)|field==10)
  }
  
  if (all(fieldhist==field)) {
    break
  }
  fieldhist=field
}

if (savefields&sum(field!=pi)>=mintiles) {
  fieldimg=array(0,dim=fielddims)
indexmat=mx.ind(field)
invisible(apply(indexmat,1,coloring))
fieldimg=fieldimg/255
name1=paste0("Field ",it,".png")
name2=paste0("Field Mines ",it," ",sum(field==exp(1))," of ",totmines,".xlsx")
writePNG(fieldimg,name1)
write.xlsx(fieldmines,name2,col.names = FALSE,row.names = FALSE)
}

flags[length(flags)+1]=sum(field==exp(1))/totmines
clearedtiles[length(clearedtiles)+1]=sum(field!=pi)/prod(dim(field))
errors[length(errors)+1]=sum(field==10)
cat("Iteration: ",it,", flags: ",sum(field==exp(1)),"/",totmines,", cleared tiles: ",sum(field!=pi),"/",prod(dim(field)),", errors: ",sum(field==10),"\n",sep = "")
}
```

fieldmoves=fieldsum!=8*pi&fieldsum!=3*pi&fieldsum!=5*pi&field!=trunc(field)&field!=exp(1)
